"""Chnages donation percentage to a float for fractional percentages. Adds new time slice tables for tracking different single instance values (network hashrate, etc)

Revision ID: 160f63e90b91
Revises: 2b1f3f73f8a2
Create Date: 2014-04-11 21:31:54.739171

"""

# revision identifiers, used by Alembic.
revision = '160f63e90b91'
down_revision = '2b1f3f73f8a2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'donation_percent', u'perc', type_=sa.Float())
    op.create_table('one_minute_type',
                    sa.Column('typ', sa.String(), nullable=False),
                    sa.Column('time', sa.DateTime(), nullable=False),
                    sa.Column('value', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('typ', 'time')
                    )
    op.create_table('one_hour_type',
                    sa.Column('typ', sa.String(), nullable=False),
                    sa.Column('time', sa.DateTime(), nullable=False),
                    sa.Column('value', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('typ', 'time')
                    )
    op.create_table('five_minute_type',
                    sa.Column('typ', sa.String(), nullable=False),
                    sa.Column('time', sa.DateTime(), nullable=False),
                    sa.Column('value', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('typ', 'time')
                    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('five_minute_type')
    op.drop_table('one_hour_type')
    op.drop_table('one_minute_type')
    ### end Alembic commands ###
