"""Renames a column

Revision ID: 219a47ab9647
Revises: 37f437076b6d
Create Date: 2014-05-08 23:25:55.369965

"""

# revision identifiers, used by Alembic.
revision = '219a47ab9647'
down_revision = '37f437076b6d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('merge_address', 'merged_coin', new_column_name='merged_type')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merge_address', sa.Column('merged_coin', sa.VARCHAR(), nullable=False))
    op.drop_column('merge_address', 'merged_type')
    ### end Alembic commands ###
