"""INTERMEDIARY: adds merged_type columns for payouts and blocks to support merge mining multiple coins. Part of a two stage migration.

Revision ID: 24b3c8992e1
Revises: 450b99a485f8
Create Date: 2014-05-08 22:46:59.600080

"""

# revision identifiers, used by Alembic.
revision = '24b3c8992e1'
down_revision = '450b99a485f8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('block', sa.Column('merged_type', sa.String(), nullable=True))
    op.add_column('bonus_payout', sa.Column('merged_type', sa.String(), nullable=True))
    op.add_column('merge_address', sa.Column('merged_coin', sa.String(), nullable=False, primary_key=True))
    op.drop_constraint('merge_address_pkey', 'merge_address')
    op.create_primary_key('merge_address_pkey', 'merge_address', ['merged_coin', 'user'])
    op.add_column('payout', sa.Column('merged_type', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payout', 'merged_type')
    op.drop_column('merge_address', 'merged_coin')
    op.drop_column('bonus_payout', 'merged_type')
    op.drop_column('block', 'merged_type')
    ### end Alembic commands ###
