"""Adds a new transaction summary table to reduce all time calculation times

Revision ID: 2b3b1f654b5
Revises: 53dcf1daebec
Create Date: 2014-07-07 19:25:17.114450

"""

# revision identifiers, used by Alembic.
revision = '2b3b1f654b5'
down_revision = '53dcf1daebec'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_summary',
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=True),
    sa.Column('count', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.txid'], ),
    sa.PrimaryKeyConstraint('transaction_id', 'user')
    )
    op.create_index('summary_user_idx', 'transaction_summary', ['user'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('summary_user_idx', table_name='transaction_summary')
    op.drop_table('transaction_summary')
    ### end Alembic commands ###
