""" Adds Status for ppagent tracking. Changes payout foreign key to point to blockhash instead of height.

Revision ID: 2db48f0c89c7
Revises: b1e627b9a0
Create Date: 2014-03-08 18:12:27.925170

"""

# revision identifiers, used by Alembic.
revision = '2db48f0c89c7'
down_revision = 'b1e627b9a0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status',
                    sa.Column('user', sa.String(), nullable=False),
                    sa.Column('worker', sa.String(), nullable=False),
                    sa.Column('status', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('user', 'worker')
                    )
    op.drop_table('payout')
    op.drop_constraint('block_pkey', 'block')
    op.create_primary_key('block_pkey', 'block', ['hash'])
    op.create_table('payout',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('blockhash', sa.String(), nullable=True),
                    sa.Column('user', sa.String(), nullable=True),
                    sa.Column('shares', sa.BigInteger(), nullable=True),
                    sa.Column('amount', sa.BigInteger(), nullable=True),
                    sa.Column('transaction_id', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['blockhash'], ['block.hash'], ),
                    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.txid'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('user', 'blockhash'),
                    sa.CheckConstraint('amount>0', 'min_payout_amount')
                    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payout')
    op.drop_table('status')
    ### end Alembic commands ###
