"""Adds average difficulty to block table

Revision ID: 322f0244224f
Revises: 52536bfc833b
Create Date: 2014-04-13 15:17:07.614894

"""

# revision identifiers, used by Alembic.
revision = '322f0244224f'
down_revision = '52536bfc833b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('block', sa.Column('difficulty_avg', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('block', 'difficulty_avg')
    ### end Alembic commands ###
