"""Removes the now un-needed merged columns from two stage migration

Revision ID: 37f437076b6d
Revises: 24b3c8992e1
Create Date: 2014-05-08 23:02:58.431148

"""

# revision identifiers, used by Alembic.
revision = '37f437076b6d'
down_revision = '24b3c8992e1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('block', 'merged')
    op.drop_column('bonus_payout', 'merged')
    op.drop_column('payout', 'merged')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payout', sa.Column('merged', sa.BOOLEAN(), server_default='false', nullable=True))
    op.add_column('bonus_payout', sa.Column('merged', sa.BOOLEAN(), server_default='false', nullable=True))
    op.add_column('block', sa.Column('merged', sa.BOOLEAN(), server_default='false', nullable=True))
    ### end Alembic commands ###
