"""Adds boolean merged mined column for payouts and blocks, along with a table for merge mining address associations

Revision ID: 450b99a485f8
Revises: 322f0244224f
Create Date: 2014-05-03 02:47:32.704020

"""

# revision identifiers, used by Alembic.
revision = '450b99a485f8'
down_revision = '322f0244224f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merge_address',
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('merge_address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user')
    )
    op.add_column(u'block', sa.Column('merged', sa.Boolean(), nullable=True, server_default="FALSE"))
    op.add_column(u'bonus_payout', sa.Column('merged', sa.Boolean(), nullable=True, server_default="FALSE"))
    op.add_column(u'payout', sa.Column('merged', sa.Boolean(), nullable=True, server_default="FALSE"))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'payout', 'merged')
    op.drop_column(u'bonus_payout', 'merged')
    op.drop_column(u'block', 'merged')
    op.drop_table('merge_address')
    ### end Alembic commands ###
