"""Adds merged_type to transactions and worker to block table

Revision ID: 53dcf1daebec
Revises: 219a47ab9647
Create Date: 2014-05-14 06:48:11.695068

"""

# revision identifiers, used by Alembic.
revision = '53dcf1daebec'
down_revision = '219a47ab9647'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('block', sa.Column('worker', sa.String(), nullable=True))
    op.add_column('transaction', sa.Column('merged_type', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'merged_type')
    op.drop_column('block', 'worker')
    ### end Alembic commands ###
