"""empty message

Revision ID: 58441c58e37e
Revises: 2db48f0c89c7
Create Date: 2014-03-09 15:17:01.996769

"""

# revision identifiers, used by Alembic.
revision = '58441c58e37e'
down_revision = '2db48f0c89c7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('status', sa.Column('time', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('status', 'time')
    ### end Alembic commands ###
